### ISSUE TITLE
Large single_cell@assays$RNA@scale.data

### ISSUE THREAD

**Issue by 1667857557** [sulab-wmu/scPagwas#26]
尊敬的邓老师，

   感谢您开发如此优秀的工具，使用中我们遇到了一个小问题，当我们纳入超过15G的大单细胞文件时，ScaleData获得了超过90G的处理后文件，我们用您提供的拆分数据分别运行scPagwas以避免报错，但在Get_CorrectBg_p这一步会需要占用超过300G内存，请问scPagwas运行时是否需要使用single_cell@assays$RNA@scale.data文件，如不需要，我们希望用single_cell@assays$RNA@scale.data <- new("dgCMatrix")来清除它以减少系统负担。此外,scPagwas处理较大单细胞文件时巨大的内存和时间消耗可能限制了它的使用，请问您是否有更好的解决方案呢？

   热切期待您的回复，祝您科研顺利！
黄钰沣

**Comment by dengchunyu** [comment]
现在还没有完美的解决办法，我们有打算将来开发python版本，不过这里有一个折中的办法是将单细胞downsample到内存能够承受的大小，进行计算，得到top的基因之后进行所有单细胞的TRS，这个方法能够得到每个细胞的TRS得分，但可能无法计算整体单细胞的pvalue，因为这样仍然需要大量内存。

**Comment by 1667857557** [comment]
我了解了，感谢您的回复
