### ISSUE TITLE
clarification on converting OR to beta for scPagwas Input

### ISSUE THREAD

**Issue by dbyzy** [sulab-wmu/scPagwas#31]
Dear scPagwas team,

Thank you very much for developing this invaluable tool for integrating scRNA and GWAS data. As we prepare our GWAS data for input into scPagwas, we have encountered some confusion regarding whether we should converse odds ratios (OR) to betas. Currently, our GWAS data includes: rsid, OR, SE, and freq.

We are uncertain whether we should: 

          Directly use the OR values by just renaming the column to beta, or
          Convert OR to beta using the formula beta = ln(OR) and calculate the SE of beta after converting OR.

Also, in the Vignettes, it is mentioned that _"it is possible to compute a conversion using the following formula: beta = ES / SE"_.  If we need to convert OR to beta, which method is appropriate, beta = ln(OR) or beta = ES / SE ?

Thank you in advance for your assistance

Regards

**Comment by dengchunyu** [comment]
If your GWAS data includes odds ratios (ORs), you should use the following formula: 𝛽=ln(OR).
beta = ES / SE : This method is suitable when there is no OR
